In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import library

In [7]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Import dataset "Data.csv"

In [8]:
print(x)

[['Briavel' 17 150000]
 ['Allysa' 17 200000]
 ['Davide' 18 540000]
 ['Allysa' 17 81000]
 ['Davide' 18 150000]
 ['Briavel' 17 230000]
 ['Allysa' 17 130000]
 ['Briavel' 17 190000]
 ['Davide' 18 99000]
 ['Briavel' 17 570000]]


In [9]:
print(y)

['No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [10]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:, 1:3])
x[:, 1:3] = impute.transform(x[:, 1:3])

In [11]:
print(x)

[['Briavel' 17.0 150000.0]
 ['Allysa' 17.0 200000.0]
 ['Davide' 18.0 540000.0]
 ['Allysa' 17.0 81000.0]
 ['Davide' 18.0 150000.0]
 ['Briavel' 17.0 230000.0]
 ['Allysa' 17.0 130000.0]
 ['Briavel' 17.0 190000.0]
 ['Davide' 18.0 99000.0]
 ['Briavel' 17.0 570000.0]]


Encoding data atribut

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 1.0 0.0 17.0 150000.0]
 [1.0 0.0 0.0 17.0 200000.0]
 [0.0 0.0 1.0 18.0 540000.0]
 [1.0 0.0 0.0 17.0 81000.0]
 [0.0 0.0 1.0 18.0 150000.0]
 [0.0 1.0 0.0 17.0 230000.0]
 [1.0 0.0 0.0 17.0 130000.0]
 [0.0 1.0 0.0 17.0 190000.0]
 [0.0 0.0 1.0 18.0 99000.0]
 [0.0 1.0 0.0 17.0 570000.0]]


Encoding data label

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 1 0 0 1 0 1 0 1]


Membagi data ke Training Set dan Tes Set

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [17]:
print(x_train)

[[1.0 0.0 0.0 17.0 130000.0]
 [0.0 0.0 1.0 18.0 150000.0]
 [0.0 1.0 0.0 17.0 150000.0]
 [1.0 0.0 0.0 17.0 81000.0]
 [1.0 0.0 0.0 17.0 200000.0]
 [0.0 1.0 0.0 17.0 190000.0]
 [0.0 0.0 1.0 18.0 99000.0]
 [0.0 1.0 0.0 17.0 230000.0]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 18.0 540000.0]
 [0.0 1.0 0.0 17.0 570000.0]]


In [20]:
print(y_train)

[0 0 0 0 1 1 0 1]


In [21]:
print(y_test)

[1 1]


Scalling data yang besar

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [23]:
print(x_train)

[[1.0 0.0 0.0 -0.5773502691896258 -0.49862755522284957]
 [0.0 0.0 1.0 1.7320508075688774 -0.07873066661413414]
 [0.0 1.0 0.0 -0.5773502691896258 -0.07873066661413414]
 [1.0 0.0 0.0 -0.5773502691896258 -1.5273749323142023]
 [1.0 0.0 0.0 -0.5773502691896258 0.9710115549076545]
 [0.0 1.0 0.0 -0.5773502691896258 0.7610631106032967]
 [0.0 0.0 1.0 1.7320508075688774 -1.1494677325663585]
 [0.0 1.0 0.0 -0.5773502691896258 1.6008568878207277]]


In [25]:
print(x_test)

[[0.0 0.0 1.0 1.7320508075688774 8.109258661255817]
 [0.0 1.0 0.0 -0.5773502691896258 8.73910399416889]]
